apps: moved misplaced fluentd conf
elastisys/compliantkubernetes-apps pull request #1
Opened 2020-11-02 08:58 UTC by pettersv

**What this PR does / why we need it**:
The configuration key useRegionEndpoint was mistakenly placed under elasticsearch config when it should have been under fluentd. This PR corrects that.

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*:

fixes #265

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [X] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/master/WIP-CHANGELOG.md)
- [X] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [X] requires running a migration script. 
        - re-run init
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

2020-11-02 12:22 UTC, OlleLarsson approved these changes
I have not checked out and applied but this looks alright to me :)

2020-11-02 12:40 UTC, danielharr commented
Perhaps the "re-run init" step could be added to the release notes as well, since this will break configuration?

2020-11-03 14:42 UTC, lentzi90 requested changes
We need an entry in the release notes for this. Something like "Move `useRegionEndpoint` from `elasticsearch` to `fluentd` in `sc-config.yaml` before upgrading."

2020-11-04 12:03 UTC, pettersv commented
> We need an entry in the release notes for this. Something like "Move `useRegionEndpoint` from `elasticsearch` to `fluentd` in `sc-config.yaml` before upgrading."

Done

2020-11-05 06:02 UTC, lentzi90 approved these changes

2020-11-19 09:22 UTC, merged