apps wc: Remove undefined macro preventing falco rule compilation
elastisys/compliantkubernetes-apps pull request #1011
Opened 2022-05-24 14:08 UTC by aarnq

**What this PR does / why we need it**:
Saw that the falco ds rollout was stuck due to a missing macro in the falco rule.
```console
Tue May 24 13:44:05 2022: Runtime error: Could not load rules file /etc/falco/rules.d/overwrites.yaml: 1 errors:
Compilation error when compiling "...": Undefined macro calico_node used in filter.
---
- macro: write_etc_common
  condition: >
...
    and not calico_node
---
. Exiting.

```

**Special notes for reviewer**:
I don't know if there is one that should be included instead.
I tried to include the one in the default rules but it did not work, it still failed to compile.

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [x] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [x] I upgraded no Chart.
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

2022-05-25 14:07 UTC, robinAwallace approved these changes

2022-05-31 12:46 UTC, Pavan-Gunda approved these changes

2022-05-31 12:48 UTC, viktor-f commented
With this we probably need to reopen https://github.com/elastisys/compliantkubernetes-apps/issues/897 since part of that issue was to add this.
@raviranjanelastisys probably knows more

2022-05-31 12:58 UTC, raviranjanelastisys commented
> With this we probably need to reopen #897 or open a new issue since part of that issue was to add this. @raviranjanelastisys probably knows more

Yes we need that and not remove the macros ...i don't think so there is still any compilations issue . This same changes has been accepted by the falco community too . Pls refer here - https://github.com/falcosecurity/falco/pull/1981/files

2022-05-31 13:00 UTC, raviranjanelastisys requested changes
We still need these macros `calico_node to be added . Please don't remove .

2022-05-31 13:00 UTC, raviranjanelastisys requested changes
We still need these macros `calico_node` to be added . Please don't remove . You can refer here and same accepted by the falco community - https://github.com/falcosecurity/falco/pull/1981/files

2022-05-31 13:23 UTC, raviranjanelastisys commented
> > 
> 
> @aarnq I am not sure if the compilations issue because of this because previous apps release were also done with the same rule i added before.

@aarnq Is this stopping release, you can remove it , as this is already be added by upstream community and this was planned to remove it too at the later stage from the override.yaml file . So i approve it

2022-05-31 13:23 UTC, raviranjanelastisys approved these changes

2022-05-31 13:50 UTC, merged