apps sc: new influx chart version, pinning retention version
elastisys/compliantkubernetes-apps pull request #120
Opened 2020-12-09 10:43 UTC by viktor-f

**What this PR does / why we need it**: New version of the influxdb chart that pins the retention image version. See this PR for the actual changes: https://github.com/elastisys/influxdb-helm-charts/pull/6

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*:  This fixes the issue of us pulling the image each time the retention is run (2 jobs every 5 mins per service cluster). 

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [ ] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [ ] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

2020-12-09 13:12 UTC, OlleLarsson requested changes
Can you update the wip change log `InfluxDB helm chart upgraded to 4.8.9` -> ´InfluxDB helm chart upgraded to 4.8.10`?

2020-12-09 13:41 UTC, viktor-f commented
> Can you update the wip change log `InfluxDB helm chart upgraded to 4.8.9` -> `InfluxDB helm chart upgraded to 4.8.10`?

Fixed now :slightly_smiling_face:

2020-12-09 14:06 UTC, OlleLarsson approved these changes

2020-12-10 11:07 UTC, lentzi90 approved these changes

2020-12-10 11:43 UTC, merged