fixes: to migration docs and kured
elastisys/compliantkubernetes-apps pull request #1207
Opened 2022-09-28 07:37 UTC by crssnd

**What this PR does / why we need it**: to fix some issues with the migration docs and kured

2022-09-29 14:08 UTC, robinAwallace requested changes

2022-09-29 14:08 UTC, robinAwallace commented on config/config/common-config.yaml
> +      botToken: ""
This is part of secret and not common-config.

2022-09-30 13:48 UTC, robinAwallace commented on config/secrets/sc-secrets.yaml
> +#    botToken: "me"
```suggestion
#    botToken: "set-me"
```

2022-09-30 13:48 UTC, robinAwallace commented on helmfile/50-applications.yaml
> +  installed: {{ .Values.kured.notification.slack.enabled }}
```suggestion
  installed: {{ and .Values.kured.enabled .Values.kured.notification.slack.enabled }}
```

2022-10-03 13:22 UTC, robinAwallace approved these changes

2022-10-10 11:22 UTC, davidumea approved these changes

2022-10-10 12:25 UTC, crssnd commented on migration/v0.25.x-v0.26.x/upgrade-apps.md
> +# Upgrade v0.25.x to v0.26.x
I ended up adding almost all the instructions :)

2022-10-10 13:35 UTC, viktor-f approved these changes

2022-10-10 13:35 UTC, viktor-f commented on migration/v0.25.x-v0.26.x/upgrade-apps.md
> +        channel: notification-channel
```suggestion
        channel: kured-notification
```

2022-10-11 06:43 UTC, merged