apps: Removed persistent volumes for prometheus
elastisys/compliantkubernetes-apps pull request #308
Opened 2021-03-09 14:09 UTC by Xartos

**What this PR does / why we need it**:
Removing persistent volumes for prometheus.

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*:
fixes #285 

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [x] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

2021-03-09 14:13 UTC, OlleLarsson approved these changes
LGTM, though I'd like you to mention in the upgrade docs that one should remove `prometheus.storage.size`(?) from the config files.

2021-03-09 14:30 UTC, viktor-f reviewed
Do we want to make this into an option instead (that defaults to no PVC)? I'm thinking mostly on the leaner apps setups we have talked about where we might not want to run InfluxDB, then we would like to have PVCs for prometheus instead.
But we could add that option when it becomes relevant.

2021-03-09 15:56 UTC, viktor-f requested changes
Nice that you made it optional

2021-03-09 15:56 UTC, viktor-f commented on WIP-CHANGELOG.md
> +- Removed persistent volumes for prometheus
```suggestion
- Persistent volumes for prometheus are now optional (disabled by default)
```

2021-03-09 15:56 UTC, viktor-f commented on migration/v0.11.x-v0.12.x/upgrade-apps.md
> +1. Delete the PVCs that are now obsolete.
```suggestion
1. If PVCs for prometheus are not enabled, then delete the PVCs that are now obsolete.
```

2021-03-11 08:34 UTC, viktor-f approved these changes
LGTM
Just rebase on main and perhaps squash a few commits

2021-03-11 10:02 UTC, OlleLarsson approved these changes

2021-03-11 10:59 UTC, merged