apps sc: add script to restore Harbor from backup
elastisys/compliantkubernetes-apps pull request #379
Opened 2021-04-12 12:45 UTC by viktor-f

**What this PR does / why we need it**: This adds the restore script for harbor. I debated putting some documentation here but I though it might be better to just have it on compliantkubernetes.io (PR with that is coming later)

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: part of elastisys/compliantkubernetes#77

**Public facing documentation PR** *(if applicable)*

Coming later

**Special notes for reviewer**:

**Checklist:**

- [ ] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [ ] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

2021-04-12 13:11 UTC, OlleLarsson commented
I don't fully understand this script.
Where is this supposed to be run, from localhost or in k8s?

2021-04-12 13:15 UTC, viktor-f commented
> I don't fully understand this script -where is this supposed to be run, from localhost or in k8s?

From local host (you can see the old instructions here: https://github.com/elastisys/ck8s-ops/tree/main/backup/harbor). Honestly I think we should rework this script, but that will be done in a later issue.

2021-04-12 13:20 UTC, OlleLarsson commented
> > I don't fully understand this script -where is this supposed to be run, from localhost or in k8s?
> 
> From local host (you can see the old instructions here: https://github.com/elastisys/ck8s-ops/tree/main/backup/harbor). Honestly I think we should rework this script, but that will be done in a later issue.

I see.

2021-04-12 13:20 UTC, OlleLarsson approved these changes

2021-04-12 14:57 UTC, Xartos requested changes
Overall nice script, but I have some comments

2021-04-12 14:57 UTC, Xartos commented on scripts/restore/restore-harbor.sh
> +        if pg_isready -h $HOSTNAME | grep "accepting connections"; then
Is this a dependency for this script (`pg_isready`)? If so, we should add something about it. I'm fine by just mentioning it on top of the file.

2021-04-12 14:57 UTC, Xartos commented on scripts/restore/restore-harbor.sh
> +          | sort | tail -n 1 | awk '{print $4}')
Should we add a prompt here verifying that this is the backup you want to restore from?

2021-04-12 14:57 UTC, Xartos commented on scripts/restore/restore-harbor.sh
> +s3_download "$1"
Thinking about it, I feel like we should have a prompt before here as well. We are in fact wiping the whole DB, so a warning should make the user at least a bit more aware if not.

2021-04-12 14:57 UTC, Xartos commented on scripts/restore/restore-harbor.sh
> +  psql -U postgres -d template1 -h $HOSTNAME -c "drop database registry;"
Same with this, should at least be mentioned in the comments

2021-04-12 14:57 UTC, Xartos commented on scripts/restore/restore-harbor.sh
> +HOSTNAME=localhost
Should you not be able to set this?

2021-04-12 14:57 UTC, Xartos commented on scripts/restore/restore-harbor.sh
> +    tar xvf harbor.tgz
```suggestion
    tar -xvf harbor.tgz -C ${backup_dir}/
```

Or maybe the backup from S3 always have this folder?

2021-04-12 14:57 UTC, Xartos commented on scripts/restore/restore-harbor.sh
> +  rmdir ${backup_dir}
```suggestion
  rm -r ${backup_dir}
```

2021-04-12 14:58 UTC, Xartos commented
I just read these comments. 
I think we should add the readme from the old instructions. Otherwise it's kind of confusing

2021-04-13 12:20 UTC, viktor-f commented
I added the instructions that I'm going to put into the official docs.

@Xartos is it ok that I leave the script as is and instead rework it in a separate issue?

2021-04-14 13:53 UTC, viktor-f commented
Added another issue to rework this script: https://github.com/elastisys/compliantkubernetes-apps/issues/386

2021-04-14 14:26 UTC, Xartos approved these changes
@viktor-f Yes, that is fine. That with the addition of the README and I think this is good to go :slightly_smiling_face:

2021-04-15 06:56 UTC, merged