apps wc & sc: default to object storage disabled
elastisys/compliantkubernetes-apps pull request #387
Opened 2021-04-14 14:12 UTC by robinelastisys

**What this PR does / why we need it**:
Object storage gets disabled by default to fasten a developers creation of a cluster for test-purposes.

**Which issue this PR fixes** 
fixes #361 

**How to enable ObjectStorage?**
Before https://github.com/elastisys/compliantkubernetes-apps quickstart 5-6:

sc-config:
Set objectStorage:type: s3
Set user:harbor:enabled: true
Set harbor:persistence:type: objectStorage
Set elasticsearch:snapshot:enabled: true
Set elasticsearch:fluentd:enabled: true
Set influxDB:backup:enabled: true
Set ingressNginx:velero:enabled: true

wc-config:
Set objectStorage:type: s3
Set ingressNginx:velero:enabled: true

ln -sf $CK8S_CONFIG_PATH/.state/kube_config_${SERVICE_CLUSTER}.yaml $CK8S_CONFIG_PATH/.state/kube_config_sc.yaml
./bin/ck8s apply sc  # Respond "n" if you get a WARN

for CLUSTER in "${WORKLOAD_CLUSTERS[@]}"; do
    ln -sf $CK8S_CONFIG_PATH/.state/kube_config_${CLUSTER}.yaml $CK8S_CONFIG_PATH/.state/kube_config_wc.yaml
    ./bin/ck8s apply wc  # Respond "n" if you get a WARN
done

**How to make "at the minimum you should configure" shorter?**
The editing of ${CK8S_CONFIG_PATH}/secrets.yaml could be removed. Other then that, It could be left as it is as https://github.com/elastisys/compliantkubernetes-apps, quickstart 5-6 isnt needed anymore when ObjectStorage is disabled be default? The "shortening" is that quickstart 5-6 isn't a must anymore.

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits

**Definition of done:**
- [x] S3 is disabled by default.
- [x] Documentation exists on how to enable and verify it.
- [x] All backups (InfluxDB, Harbor, etc.) which depend on S3 are disabled by default.
- [x] Harbor (which is the biggest consumer of S3) is either using PVCs for persistence or is disabled by default.
- [x] The "at the minimum you should configure" sections in documentation are way shorter.

2021-04-15 07:59 UTC, viktor-f requested changes
A good start. :slightly_smiling_face: 

Found one error in the harbor config.

Also object storage should only be disabled by default for the dev flavor. So either move these changes to the dev config files (e.g. `config/config/flavors/dev-sc.yaml`) or undo these changes in the prod flavor config files (e.g. `config/config/flavors/prod-sc.yaml`).

2021-04-15 07:59 UTC, viktor-f commented on config/config/sc-config.yaml
> +  enabled: false
Harbor should still be enabled. But disable Harbor backups on line 154: https://github.com/elastisys/compliantkubernetes-apps/blob/25bd108d6832661522b4d84537eeecd11c109aca/config/config/sc-config.yaml#L154
```suggestion
  enabled: true
```

2021-04-15 07:59 UTC, viktor-f commented on WIP-CHANGELOG.md
> +- Default to object storage disabled.
```suggestion
- Default to object storage disabled for the dev flavor.
```

2021-04-15 08:09 UTC, OlleLarsson reviewed
Looks good, but I agree with Viktor's comments that these changes should be in the dev flavor.

2021-04-16 07:22 UTC, robinelastisys commented
Corrections have been made! :+1:

2021-04-16 08:05 UTC, viktor-f requested changes
One miss, but otherwise looks good.
The merge conflict should be easy to fix. If you are uncertain how I can show you via slack :slightly_smiling_face:

2021-04-16 08:05 UTC, viktor-f commented on config/config/flavors/dev-wc.yaml
> +  enabled: true
```suggestion
  enabled: false
```

2021-04-16 09:04 UTC, viktor-f approved these changes

2021-04-16 10:20 UTC, OlleLarsson approved these changes

2021-04-19 06:39 UTC, merged