Rook monitoring
elastisys/compliantkubernetes-apps pull request #435
Opened 2021-05-06 13:00 UTC by lentzi90

**What this PR does / why we need it**:
This adds ServiceMonitors, PrometheusRules (alerts) and Grafana dashboards for monitoring Rook-Ceph. It is based on the docs [here](https://rook.io/docs/rook/v1.6/ceph-monitoring.html) which uses the resources [here](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph/monitoring).

**Which issue this PR fixes**: fixes #381

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

The current monitoring configuration is starting to show its limits unfortunately. We run Rook both in SC and WC. We want alerts from both instances, but we should not push these alerts to the users (and probably not the metrics either).
I'm getting a bit lost in this and there is still somethings that doesn't quite work. Some help would be much appreciated.

This is how I understand it:

- We deploy kube-prometheus-stack in both SC and WC, but don't include the default PrometheusRules here since we have our own slightly tweaked version of them.
- We deploy `prometheus-alerts` (our own chart with the default PrometheusRules and some extra) 2 times in SC to be used with SC-prometheus and wc-reader.
- We also deploy `prometheus-alerts` in WC. There it provides metrics and alerts to the user, and metrics only to us. There is no way for us currently to separate these. I added a separate values template for this so it is at least separate from the wc-reader alerts we deploy in SC.

What is not working? I cannot seem to get metrics from WC to work in Grafana. They do get to prometheus in WC but I'm not sure about the rest. Maybe I'm missing some labels to make them picked up by wc-reader?

TODO:

- Get metrics from WC working
- Tests? Or include in QA procedures?

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [x] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

2021-05-06 14:57 UTC, viktor-f commented
I'm not seeing anything that would explain your problems, but I could look at this with you tomorrow.

2021-05-07 07:39 UTC, lentzi90 commented
Thanks to @viktor-f I got the WC metrics working! With this I think it is good enough to merge. :slightly_smiling_face: 
There is more work to be done to improve how the monitoring works though, so I'll create a follow up issue for it. The dashboards could also be improved to support multiple workload clusters. 1 of them already does this but the other do not have a "cluster" selector.

2021-05-26 12:33 UTC, Xartos requested changes

2021-05-26 12:33 UTC, Xartos commented on migration/v0.14.x-v0.15.x/upgrade-apps.md
> +1. Set `monitoring.rook.enabled` to `false` in both `sc-config.yaml` and `wc-config.yaml` if you don't want or need to monitor Rook.
Move to 0.15->0.16 script

2021-05-26 12:33 UTC, Xartos commented on config/config/sc-config.yaml
> +    enabled: true
Shouldn't this be `false` by default?

2021-05-26 12:48 UTC, Xartos reviewed
reset request change
EDIT: didn't work ... I'll wait for approves and approve myself then

2021-05-26 13:48 UTC, viktor-f approved these changes

2021-05-26 14:33 UTC, OlleLarsson approved these changes

2021-05-26 14:34 UTC, merged