apps sc: logs-retention run even when their is no logs to delete
elastisys/compliantkubernetes-apps pull request #443
Opened 2021-05-11 09:59 UTC by robinelastisys

**What this PR does / why we need it**:
The sc-logs-retention CronJob failed when their was no logs to be deleted. This is now fixed.

**Which issue this PR fixes** 
fixes #418 

**Test** 
s3cmd -c ~/.s3cfg del --recursive s3://exoscale-sc-logs/logs/{The latest folder} until all logs are gone
./bin/ck8s ops kubectl sc create job sc-logs-retention-1 --namespace fluentd --from=cronjob/sc-logs-retention

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [x] Some test is done to check if the problem still persists.

2021-05-12 08:17 UTC, Xartos requested changes
For some reason I cant reproduce this issue locally. Maybe the bash versions differ and thus mapfile.
Do you know what bash version that is used in the container? 

It feels like we're going around the issue with this solution. As far as I understand mapfile is returning an empty array if there's no input. Maybe there's a flag for this?

2021-05-12 09:11 UTC, robinelastisys commented on WIP-CHANGELOG.md
> +- The dry-run and appy command now checks against the state of the cluster while ran
It is indeed a bit tricky to re-produce. You need to spam _s3cmd -c ~/.s3cfg del --recursive s3://exoscale-sc-logs/logs/20210512/_ until you reach _WARNING: Remote list is empty._ Then run
_./bin/ck8s ops kubectl sc create job sc-logs-retention-1 --namespace fluentd --from=cronjob/sc-logs-retention_ quickly. The pod will then get status "Error" and you can read its log by ._/bin/ck8s ops kubectl sc logs {pod name} --namespace fluentd_

Yup, leftover!

2021-05-12 09:14 UTC, robinelastisys commented on helmfile/charts/sc-logs-retention/scripts/logs-retention.sh
> +set -eo pipefail
Exactly. It gets to be an issue. If you have _set -u_, the script will throw an error no matter what. Even if you just want to do an if-case to check if the variable is indeed unbound.

Will check again if their is a better solution.

2021-05-14 14:33 UTC, Xartos commented on WIP-CHANGELOG.md
> +- The dry-run and appy command now checks against the state of the cluster while ran
I didn't try to reproduce it in the cluster I just tried locally with this script

```bash
#!/bin/bash

set -euo pipefail

SC_LOG_BACKUPS=$(echo -e "20210423/\n20210424/\n20210425/\n20210426/\n20210427/\n")

declare -a SC_LOG_BACKUPS_LATEST
declare -a SC_LOG_BACKUPS_REST
mapfile -t SC_LOG_BACKUPS_LATEST < <(echo "${SC_LOG_BACKUPS}" | tail -n "7")
mapfile -t SC_LOG_BACKUPS_REST < <(echo "${SC_LOG_BACKUPS}" | head -n "-7")

echo "latest"
echo "${SC_LOG_BACKUPS_LATEST[@]}"
echo "rest"
echo "${SC_LOG_BACKUPS_REST[@]}"
```

And that seems to work. So either the bash versions differ, or my assumption that `SC_LOG_BACKUPS` consists of `20210423/\n20210424/\n20210425/\n20210426/\n20210427/\n` is false.

2021-05-25 07:48 UTC, robinelastisys commented
I pause with this a bit as my cluster needs to stack enough logs and so forth.

2021-05-28 13:29 UTC, robinelastisys commented
Now i have presented a solution :+1:

2021-05-28 14:11 UTC, Xartos requested changes
Nice, this was a solution I was looking for :+1: Just some minor format stuff

2021-05-28 14:11 UTC, Xartos commented on helmfile/charts/sc-logs-retention/scripts/logs-retention.sh
> +if [ ${#SC_LOG_BACKUPS_REST[*]} -eq 0 ]; then echo "No backups were found for automatic removal"; else
I would like to have this in the same format as the rest of the file, so fix indentation remove this one-liner

```suggestion
if [ ${#SC_LOG_BACKUPS_REST[*]} -eq 0 ]; then
  echo "No backups were found for automatic removal"
else
```

2021-05-28 14:11 UTC, Xartos commented on WIP-CHANGELOG.md
> +- The sc-logs-retention cronjob now runs without error even if no backups were found for automatic removal
I guess this is some merge conflict miss. Just remove everything else but this

2021-06-01 12:54 UTC, Xartos requested changes
Still some things

2021-06-01 12:54 UTC, Xartos commented on WIP-CHANGELOG.md
> +- CK8S version validation accepts version number if exactly at the release tag, otherwise commit hash of current commit. "any" can still be used to disable validation.
You can remove these lines
```suggestion
```

2021-06-01 12:54 UTC, Xartos commented on helmfile/charts/sc-logs-retention/scripts/logs-retention.sh
>  echo "${SC_LOG_BACKUPS_LATEST[@]}"
I would like to have all this properly indented. Like this:

```suggestion
if [ ${#SC_LOG_BACKUPS_REST[*]} -eq 0 ]; then
  echo "No backups were found for automatic removal";
else
  echo "Listing ${RETENTION_DAYS} latest backups"
  echo "${SC_LOG_BACKUPS_LATEST[@]}"
```

And so on...

2021-06-02 12:13 UTC, viktor-f approved these changes

2021-06-03 07:12 UTC, robinelastisys commented on helmfile/charts/sc-logs-retention/scripts/logs-retention.sh
>      sed 's!'"${BACKUP_PREFIX}"'!!')
Done! :+1:

2021-06-03 13:13 UTC, Xartos approved these changes
LGTM!

2021-06-03 14:15 UTC, merged