apps wc: Fix fluentd configuration
elastisys/compliantkubernetes-apps pull request #57
Opened 2020-11-11 12:17 UTC by OlleLarsson

Removes leftover nodeSelector and tolerations in the values file. Now
everything is only taken from the configuration files.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [ ] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [ ] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

2020-11-12 13:25 UTC, danielharr requested changes
Nice! Just a small typo in the changelog, otherwise LGTM :slightly_smiling_face:

2020-11-12 13:25 UTC, danielharr commented on WIP-CHANGELOG.md
> +- The wc fluentd tolerations and nodeSelector configuration options are now only sepcified in the configuration file.
```suggestion
- The wc fluentd tolerations and nodeSelector configuration options are now only specified in the configuration file.
```

2020-11-12 15:14 UTC, danielharr approved these changes
LGTM! :slightly_smiling_face:

2020-11-13 07:09 UTC, Xartos approved these changes
LGTM!

2020-11-13 07:13 UTC, viktor-f approved these changes

2020-11-13 07:22 UTC, merged