apps: fluentd can now create and write to .orphaned indexes
elastisys/compliantkubernetes-apps pull request #793
Opened 2022-02-01 07:59 UTC by Pavan-Gunda

**What this PR does / why we need it**:
This PR allows fluentd to create and write to .orphaned indexes
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #746 

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [x] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [x] I upgraded no Chart.
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

**Pipeline config** *(if applicable)*
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline in `pipeline/config`.

2022-02-01 08:02 UTC, Pavan-Gunda commented
I could not recreate the scenarios in the issue, but I tested to make sure fluentd cannot read from it, but just create and write to .orphaned indexes.

2022-02-01 08:22 UTC, OlleLarsson requested changes
LGTM expect that now users will be able to read logs from the orphaned indices.
We said that they should not be able to do that.

2022-02-01 08:22 UTC, OlleLarsson commented on helmfile/values/opensearch/configurer.yaml.gotmpl
> +          - ".orphaned-*"
```suggestion
```

2022-02-01 08:22 UTC, OlleLarsson commented on helmfile/values/opensearch/configurer.yaml.gotmpl
> +          - ".orphaned-*"
```suggestion
```

2022-02-01 08:26 UTC, OlleLarsson commented on WIP-CHANGELOG.md
> + - Fluentd can now create an index .orphaned indexes and write to them
```suggestion
 - Fluentd can now properly handle and write orphaned documents to Opensearch when using the index per namespace feature.

```

2022-02-07 07:45 UTC, Xartos reviewed
LGTM. But I'll wait to approve untiil either olle or andré gives their blessing

2022-02-08 07:36 UTC, aarnq approved these changes
Otherwise I think it looks good.

2022-02-08 07:36 UTC, aarnq commented on WIP-CHANGELOG.md
> +  The orphaned documents will be written to `.orpahaned-...` indices, which a users does not have access to read from.
```suggestion
  The orphaned documents will be written to `.orphaned-...` indices, which a user does not have access to read from.
```

2022-02-09 14:49 UTC, OlleLarsson approved these changes

2022-02-09 23:12 UTC, merged