apps: add support for baremetal provider
elastisys/compliantkubernetes-apps pull request #89
Opened 2020-11-19 14:45 UTC by pettersv

**What this PR does / why we need it**:

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #231

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [ ] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [ ] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

2020-11-19 15:00 UTC, viktor-f requested changes
Added some comments where you could simplify some things

2020-11-19 15:00 UTC, viktor-f commented on bin/init.bash
> +          ;;
Same here

2020-11-20 12:09 UTC, pettersv commented on bin/init.bash
> +          ;;
This is by choice after a conversation with @Xartos As this is experimental, we want to keep bare-metal stuff separate as to make it easier to change settings.

2020-11-20 12:09 UTC, pettersv commented on bin/init.bash
> +          ;;
See above

2020-11-20 12:09 UTC, pettersv commented on bin/init.bash
> +          ;;
See above

2020-11-20 12:33 UTC, viktor-f requested changes
Maybe mention "baremetal" earlier in the readme as well under the section "Cloud providers" (line 46 onward). Otherwise it looks good.

2020-11-20 13:35 UTC, viktor-f approved these changes

2020-11-20 13:44 UTC, Xartos reviewed
I'll have to test it, but from the looks of it I think it looks good

2020-11-20 13:55 UTC, pettersv commented
> I'll have to test it, but from the looks of it I think it looks good

What?! Don't you trust me? ;)

2020-11-20 15:23 UTC, Xartos approved these changes
Testing worked out fine! Just fix the pre-commit errors before merging

2020-11-23 08:51 UTC, merged